name: entity
version: 1.1.0
description: A simple ORM for Relational and NoSQL database, such as Couchbase and PostgreSQL.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: https://github.com/rikulo/entity
documentation: https://github.com/rikulo/entity
dev_dependencies:
  test: any
  postgresql2: any
  charcode: any
  rikulo_commons: ">=2.0.0"
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
